import React, { useEffect, useState } from 'react';
import { useStore } from '../store/appStore';
import { ArrowLeft, Download, FileText, File, BarChart } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { exportToPDF, exportToMarkdown } from '../tools/exportTool';
import { exportToDOCX } from '../tools/docxTool';
import { formatCitation, CitationStyle } from '../tools/citationTool';
import { generateChartData, ChartData } from '../tools/visualizer';

export const ReportView: React.FC = () => {
  const { currentSessionId, sessions, showReportView, setShowReportView } = useStore();
  const session = sessions.find(s => s.id === currentSessionId);
  const [chartData, setChartData] = useState<ChartData | null>(null);
  const [citationStyle, setCitationStyle] = useState<CitationStyle>('APA');
  const [loadingChart, setLoadingChart] = useState(false);

  useEffect(() => {
    if (session?.synthesis && showReportView) {
      setLoadingChart(true);
      generateChartData(session.synthesis)
        .then(setChartData)
        .finally(() => setLoadingChart(false));
    }
  }, [session?.synthesis, showReportView]);

  if (!showReportView || !session || !session.synthesis) return null;

  // Simple CSS Bar Chart Component
  const SimpleBarChart = ({ data }: { data: ChartData }) => {
    const max = Math.max(...data.datasets[0].data);
    return (
      <div className="my-8 p-6 bg-gray-50 dark:bg-horizon-900/50 rounded-xl border border-gray-200 dark:border-horizon-700">
        <h4 className="text-center font-bold text-gray-700 dark:text-gray-200 mb-6">{data.title}</h4>
        <div className="flex items-end justify-around h-48 gap-2">
          {data.datasets[0].data.map((value, i) => (
            <div key={i} className="flex flex-col items-center flex-1 group">
               <div className="text-xs text-gray-500 mb-1 opacity-0 group-hover:opacity-100 transition-opacity">{value}</div>
               <div 
                 className="w-full max-w-[40px] bg-horizon-500 rounded-t hover:bg-horizon-400 transition-all relative"
                 style={{ height: `${(value / max) * 100}%` }}
               ></div>
               <div className="text-[10px] text-gray-500 mt-2 text-center truncate w-full">{data.labels[i]}</div>
            </div>
          ))}
        </div>
      </div>
    );
  };

  const getUniqueSourceUrls = (): string[] => {
    if (!session.tasks) return [];
    
    // Safely extract and filter URLs
    const allUrls = session.tasks.flatMap(t => t.sourceUrls || []);
    const validUrls = allUrls.filter((url): url is string => typeof url === 'string' && url.trim().length > 0);
    return Array.from(new Set(validUrls));
  };

  const uniqueSourceUrls = getUniqueSourceUrls();

  return (
    <div className="absolute inset-0 z-20 bg-slate-50 dark:bg-horizon-900 flex flex-col animate-in slide-in-from-bottom-10 duration-300">
      <div className="flex items-center justify-between p-4 border-b border-gray-200 dark:border-horizon-700 bg-white dark:bg-horizon-800">
        <button 
          onClick={() => setShowReportView(false)}
          className="flex items-center gap-2 text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white transition-colors"
        >
          <ArrowLeft size={20} /> Back to Research
        </button>
        <div className="flex items-center gap-2">
           <button 
            onClick={() => exportToMarkdown(session.title, session.synthesis!)}
            className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-gray-700 hover:bg-gray-600 text-white text-sm transition-colors"
          >
            <File size={16} /> MD
          </button>
           <button 
            onClick={() => exportToDOCX(session.title as string, session.synthesis as string)}
            className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-blue-700 hover:bg-blue-600 text-white text-sm transition-colors"
          >
            <FileText size={16} /> DOCX
          </button>
          <button 
            onClick={() => exportToPDF(session.title as string, session.synthesis as string)}
            className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-horizon-500 hover:bg-horizon-400 text-white text-sm transition-colors"
          >
            <Download size={16} /> PDF
          </button>
        </div>
      </div>
      
      <div className="flex-1 overflow-y-auto p-4 md:p-8 bg-slate-50 dark:bg-horizon-900">
        <div className="max-w-4xl mx-auto bg-white dark:bg-horizon-800 p-8 md:p-12 rounded-xl shadow-xl border border-gray-200 dark:border-horizon-700 transition-colors duration-300">
          <h1 className="text-3xl font-bold text-slate-900 dark:text-white mb-2 font-mono">{session.title}</h1>
          <p className="text-gray-500 dark:text-gray-400 mb-8 border-b border-gray-200 dark:border-horizon-700 pb-4 flex justify-between items-center">
            <span>Generated by Horizon</span>
            <span className="text-sm">{new Date(session.updatedAt).toLocaleDateString()}</span>
          </p>

          {/* Dynamic Chart Section */}
          {loadingChart && <div className="h-48 flex items-center justify-center text-gray-500"><BarChart className="animate-pulse mr-2"/> Analyzing data...</div>}
          {chartData && !loadingChart && <SimpleBarChart data={chartData} />}

          <div className="prose prose-lg max-w-none dark:prose-invert">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{session.synthesis}</ReactMarkdown>
          </div>
          
          {/* Enhanced Citations Section */}
          {uniqueSourceUrls.length > 0 && (
            <div className="mt-16 pt-8 border-t border-gray-200 dark:border-horizon-700 page-break-inside-avoid">
              <div className="flex justify-between items-center mb-6">
                <h3 className="text-xl font-semibold text-slate-800 dark:text-white">References</h3>
                <div className="flex bg-gray-100 dark:bg-horizon-900 rounded-lg p-1 border border-gray-200 dark:border-horizon-700">
                  {(['APA', 'MLA', 'CHICAGO'] as CitationStyle[]).map(style => (
                    <button
                      key={style}
                      onClick={() => setCitationStyle(style)}
                      className={`px-3 py-1 text-xs rounded-md transition-colors ${citationStyle === style ? 'bg-white shadow-sm text-slate-800 dark:bg-horizon-600 dark:text-white' : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200'}`}
                    >
                      {style}
                    </button>
                  ))}
                </div>
              </div>
              
              <ul className="space-y-4">
                {uniqueSourceUrls.map((url, i) => (
                  <li key={i} className="text-sm text-gray-600 dark:text-gray-300 bg-gray-50 dark:bg-horizon-900/50 p-3 rounded-lg border border-gray-200 dark:border-horizon-700/50">
                    {formatCitation({ url }, citationStyle)}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};