import React from 'react';
import { useStore } from '../store/appStore';
import { ArrowLeft, Download, FileText, File } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { exportToPDF, exportToMarkdown } from '../tools/exportTool';

export const ReportView: React.FC = () => {
  const { currentSessionId, sessions, showReportView, setShowReportView } = useStore();
  const session = sessions.find(s => s.id === currentSessionId);

  if (!showReportView || !session || !session.synthesis) return null;

  return (
    <div className="absolute inset-0 z-20 bg-horizon-900 flex flex-col">
      <div className="flex items-center justify-between p-4 border-b border-horizon-700 bg-horizon-800">
        <button 
          onClick={() => setShowReportView(false)}
          className="flex items-center gap-2 text-gray-300 hover:text-white transition-colors"
        >
          <ArrowLeft size={20} /> Back to Research
        </button>
        <div className="flex items-center gap-2">
           <button 
            onClick={() => exportToMarkdown(session.title, session.synthesis!)}
            className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-horizon-700 hover:bg-horizon-600 text-white text-sm transition-colors"
          >
            <File size={16} /> Markdown
          </button>
          <button 
            onClick={() => exportToPDF(session.title, session.synthesis!)}
            className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-horizon-500 hover:bg-horizon-400 text-white text-sm transition-colors"
          >
            <Download size={16} /> Export PDF
          </button>
        </div>
      </div>
      
      <div className="flex-1 overflow-y-auto p-8 bg-horizon-900">
        <div className="max-w-4xl mx-auto bg-horizon-800 p-12 rounded-xl shadow-xl border border-horizon-700">
          <h1 className="text-3xl font-bold text-white mb-2">{session.title}</h1>
          <p className="text-gray-400 mb-8 border-b border-horizon-700 pb-4">
            Generated by Horizon on {new Date(session.updatedAt).toLocaleDateString()}
          </p>
          <div className="prose prose-invert prose-lg max-w-none">
            <ReactMarkdown>{session.synthesis}</ReactMarkdown>
          </div>
          
          {session.tasks && (
            <div className="mt-12 pt-8 border-t border-horizon-700">
              <h3 className="text-xl font-semibold text-white mb-4">References & Sources</h3>
              <ul className="space-y-2">
                {session.tasks.flatMap(t => t.sourceUrls || []).map((url, i) => (
                  <li key={i} className="text-sm">
                    <a href={url} target="_blank" rel="noreferrer" className="text-horizon-400 hover:underline break-all">
                      {url}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};