import jsPDF from 'jspdf';

export const exportToPDF = (title: string, content: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - (margin * 2);
  const lineHeight = 6;
  
  let y = 20;

  const checkPageBreak = (neededHeight: number) => {
    if (y + neededHeight > pageHeight - margin) {
      doc.addPage();
      y = 20;
    }
  };

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  const titleLines = doc.splitTextToSize(title, maxWidth);
  doc.text(titleLines, margin, y);
  y += (titleLines.length * 10) + 10;
  
  // Timestamp
  doc.setFont("helvetica", "italic");
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated by Horizon AI • ${new Date().toLocaleDateString()}`, margin, y);
  doc.setTextColor(0);
  y += 15;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  const lines = content.split('\n');

  lines.forEach((line) => {
    const trimmed = line.trim();
    
    if (trimmed.startsWith('## ')) {
        const text = trimmed.replace(/^#+\s*/, '');
        checkPageBreak(15);
        y += 5;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(16);
        doc.text(text, margin, y);
        y += 10;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);
    } else if (trimmed.startsWith('# ')) {
        const text = trimmed.replace(/^#+\s*/, '');
        checkPageBreak(20);
        y += 8;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(18);
        doc.text(text, margin, y);
        y += 12;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);
    } else if (trimmed.startsWith('### ')) {
        const text = trimmed.replace(/^#+\s*/, '');
        checkPageBreak(12);
        y += 4;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(13);
        doc.text(text, margin, y);
        y += 8;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);
    } else if (trimmed.length === 0) {
        y += 4;
    } else {
        // Body text handling
        const cleanText = trimmed.replace(/\*\*/g, '').replace(/\*/g, ''); // Remove simple markdown bold/italic markers
        const splitText = doc.splitTextToSize(cleanText, maxWidth);
        const blockHeight = splitText.length * lineHeight;
        
        checkPageBreak(blockHeight);
        
        doc.text(splitText, margin, y);
        y += blockHeight;
    }
  });
  
  // Add Footer with Page Numbers
  const pageCount = doc.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
  }

  doc.save(`${title.replace(/[^a-z0-9]/gi, '_').substring(0, 30)}_Report.pdf`);
};

export const exportToMarkdown = (title: string, content: string) => {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download =(`${title.replace(/[^a-z0-9]/gi, '_').substring(0, 30)}_Report.md`);
  a.click();
  URL.revokeObjectURL(url);
};